# Generated by Django 4.1.7 on 2023-03-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dubplates', '0002_track_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='url',
            new_name='download_url',
        ),
    ]
