# Generated by Django 4.1.7 on 2023-04-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dubplates', '0003_rename_url_track_download_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
