# Generated by Django 4.1.7 on 2023-04-19 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_dubplates', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='track_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_user', to=settings.AUTH_USER_MODEL)),
                ('watched_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_track', to='django_dubplates.track')),
            ],
        ),
    ]
