# Generated by Django 4.1.7 on 2023-04-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dubplates', '0005_alter_track_owner_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='watched_track',
            new_name='watched_tracks',
        ),
    ]
