# Generated by Django 4.1.7 on 2023-04-28 22:21

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_dubplates', '0006_rename_watched_track_watchlist_watched_tracks'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrackRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', multiselectfield.db.fields.MultiSelectField(choices=[('user_owns_track', 'This User Owns This Track'), ('user_watching_track', 'This User Is Watching This Track'), ('user_purchased_copy', 'This User Has Purchased a Copy of This Track')], max_length=19)),
            ],
        ),
        migrations.RemoveField(
            model_name='track',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
        migrations.AddField(
            model_name='usertrackrelationship',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertrackrel_track', to='django_dubplates.track'),
        ),
        migrations.AddField(
            model_name='usertrackrelationship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertrackrel_user', to='django_dubplates.user'),
        ),
        migrations.AddField(
            model_name='track',
            name='track_user_relationships',
            field=models.ManyToManyField(through='django_dubplates.UserTrackRelationship', to='django_dubplates.user'),
        ),
    ]
