# Generated by Django 4.1.7 on 2023-05-08 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_dubplates', '0007_usertrackrelationship_remove_track_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_user_relationships',
            field=models.ManyToManyField(through='django_dubplates.UserTrackRelationship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertrackrelationship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertrackrel_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
